#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM devdotnetorg/libgpiod:1.6.3 AS sourcelibgpiod

FROM mcr.microsoft.com/dotnet/runtime:5.0-alpine AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["src/WeatherStation.Sensors/WeatherStation.Sensors.csproj", "."]
RUN dotnet restore "./WeatherStation.Sensors.csproj"
COPY /src/WeatherStation.Sensors/. .
WORKDIR "/src/."
RUN dotnet build "WeatherStation.Sensors.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WeatherStation.Sensors.csproj" -c Release -o /app/publish

FROM base AS final
MAINTAINER DevDotNet.Org <anton@devdotnet.org>
LABEL maintainer="DevDotNet.Org <anton@devdotnet.org>"
WORKDIR /app
COPY --from=publish /app/publish .
# Get libgpiod
COPY --from=sourcelibgpiod /artifacts.zip /

# Add Libgpiod
RUN apk update \
	&& apk add --no-cache --upgrade zip \
	&& unzip -o /artifacts.zip -d / \
	&& apk del zip \
	&& rm /artifacts.zip \
#Cleaning
	&& rm -rf /var/lib/{cache,log}/ \
	&& rm -rf /var/lib/apt/lists/*.lz4 \
	&& rm -rf /var/log/* \
	&& rm -rf /tmp/* /var/tmp/* \
	&& rm -rf /usr/share/doc/ \
	&& rm -rf /usr/share/man/ \
	&& rm -rf /var/cache/apk/*

VOLUME ["/app/config"]

ENTRYPOINT ["dotnet", "WeatherStation.Sensors.dll"]
